language: python
python:
- 3.7
install:
- pip install -r requirements.txt
- pip install codacy-coverage
script:
- cd MVPTFG
deploy:
  buildpack: python
  provider: heroku
  app: mvp-tfg
  strategy: git
  api_key: $HEROKU_AUTH_TOKEN
  on:
    branch: develop