# Generated by Django 3.1.7 on 2021-03-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skin_Lesion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.TimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('creation_date', models.TimeField(auto_now_add=True)),
                ('skin_lesion', models.ManyToManyField(to='main.Skin_Lesion')),
            ],
        ),
        migrations.CreateModel(
            name='Custom_User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.TextField(max_length=10)),
                ('user_pass', models.TextField(max_length=10)),
                ('creation_date', models.TimeField(auto_now_add=True)),
                ('date_of_birth', models.DateField()),
                ('active', models.BooleanField()),
                ('dossier', models.ManyToManyField(blank=True, to='main.Dossier')),
            ],
        ),
    ]
